### ISSUE TITLE
몸에 박힌 화살들 빼주세요.

### ISSUE THREAD

**Issue by happy-spark** [IngGameTeam/inggame#161]
미니게임 시작할 때, 또는 로비로 이동했을 때 몸에 박힌 화살들 없애주세요. 블록숨바꼭질 같은 미니게임들은 몸에 화살이 박혀있으면 다 보이는 것 같아요.

**Comment by Bruce0203** [comment]
이전에도 조치를 취해서 해결했지만, 아직도 나는 걸 직접 보면 원인을 찾아보도록 하겠습니다
