### ISSUE TITLE
축구에서 골을 넣으면 모든 플레이어가 중심 위치로 이동하게 해주세요.

### ISSUE THREAD

**Issue by happy-spark** [IngGameTeam/inggame#171]
골을 넣으려면 대체적으로 상대방 골대 앞까지 가야 하고 골을 넣으면 공만 가운데로 이동합니다. 그때 상대 팀 플레이어는 훨씬 유리해집니다. 그리고 이게 반복되기 때문에 의미 없는 게임이 될 수 있습니다. 축구에서 골을 넣으면 모든 플레이어가 중심 위치로 이동하게 해주세요.

**Comment by Bruce0203** [comment]
해결했습니다 https://github.com/IngGameTeam/inggame/commit/0b2c9f481cfe7d1e2a586a605fae7abfd7b5a059
