### ISSUE TITLE
아이템 복사 버그

### ISSUE THREAD

**Issue by happy-spark** [IngGameTeam/inggame#172]
로비에 있는 미니게임 상점에서 아이템을 구매하고 엔더상자에 넣어둔 후 미니게임을 시작하거나 재접속 등(인벤토리가 새로고침(?) 될 때)마다 구매했던 아이템이 다시 인벤토리로 들어옵니다.

**Comment by Bruce0203** [comment]
아이템 능력은 갯수는 소지하고 있는 양에 따라 발동하지 않으므로 문제가 없습니다

**Comment by happy-spark** [comment]
물론 일부 아이템들은 그렇지만, 폭죽이나, 메테오 같은 소모성 아이템들은 복사를 방지해야 한다고 생각합니다.

**Comment by happy-spark** [comment]
> 아이템 능력은 갯수는 소지하고 있는 양에 따라 발동하지 않으므로 문제가 없습니다

물론 일부 아이템들은 그렇지만, 폭죽이나, 메테오 같은 소모성 아이템들은 복사를 방지해야 한다고 생각합니다.

**Comment by Bruce0203** [comment]
소모성 아이템을 따로 어디다 두지못하게 상자 상호-작용을 비활성화 했습니다
