### ISSUE TITLE
미니게임에서 로비 전용 아이템을 가져올 수 있습니다.

### ISSUE THREAD

**Issue by happy-spark** [IngGameTeam/inggame#173]
다음 사진 처럼 로비 전용 아이템을 들고 게임을 시작하면 게임 내에서 로비 전용 아이템을 사용할 수 있게 됩니다.

![image](https://user-images.githubusercontent.com/107300540/200334460-600ff9fe-2064-4b8b-878a-3634a80b6bfd.png)

**Comment by Bruce0203** [comment]
해결했습니다 https://github.com/IngGameTeam/inggame/commit/a00e70992f5a1846d2e6a92d78dfc6582a02bc8e
