### ISSUE TITLE
빌드배틀에서 TNT 터트리는 방법 2개 있습니다.

### ISSUE THREAD

**Issue by happy-spark** [IngGameTeam/inggame#174]
첫 번째는 다음 사진과 같이 빌드배틀에서 TNT가 들어있는 마인카트를 설치하고 터트리면 블록이 파괴됩니다.

![image](https://user-images.githubusercontent.com/107300540/200502896-b72ee027-4757-4288-8e25-88fd643adada.png)

두 번째는 발사기를 이용한 TNT 점화입니다.
![image](https://user-images.githubusercontent.com/107300540/200504640-5bdf5e23-d765-4179-8ffd-bee821fff92a.png)

**Comment by Bruce0203** [comment]
감사합니다 #104 이슈와 중복되는 것 같습니다
