### ISSUE TITLE
랜덤무기전쟁 게임에서 양털로 블록을 쌓고 맵 이탈이 가능합니다.

### ISSUE THREAD

**Issue by happy-spark** [IngGameTeam/inggame#175]
랜덤무기전쟁 게임에서 양털로 블록을 쌓고 맵 이탈이 가능합니다.
![image](https://user-images.githubusercontent.com/107300540/200505340-572e916d-7aaf-43fd-b16d-0e4f8e193ba7.png)

**Comment by Bruce0203** [comment]
실제로 중심으로부터 300x300 을 넘어갈 수 없도록 하는 장치가 있습니다 그래서 넘어가도 버그를 일으키지 않습니다.
오히려 허공에서 긴장감있게 플레이할 수 있어서 냅두고자 합니다
