### ISSUE TITLE
황금 체력 유지 버그

### ISSUE THREAD

**Issue by happy-spark** [IngGameTeam/inggame#176]
게임에서 황금 체력을 얻고 승리 한 후 로비로 돌아가면 황금 체력이 유지된 상태로 돌아가게 됩니다. 그리고 이대로 게임을 시작해도 황금 체력이 유지됩니다.
![image](https://user-images.githubusercontent.com/107300540/200506503-a875a8f8-c5bc-4e0c-b55a-f1308bcaf7f9.png)

**Comment by Bruce0203** [comment]
해결했습니다 https://github.com/IngGameTeam/inggame/commit/21d558121586d8a1e556e50d9a12e06654ce90fa
