### ISSUE TITLE
미니게임 아이템 가져오기 버그

### ISSUE THREAD

**Issue by happy-spark** [IngGameTeam/inggame#177]
https://github.com/IngGameTeam/inggame/issues/173 이 버그와 같은 원리로 미니게임에 있던 아이템을 로비로 가져올 수도 있습니다. 이 원리를 한번 더 이용하면, 로비로 가져왔던 아이템을 다음 게임에서 사용할 수 있습니다.

**Comment by Bruce0203** [comment]
#173 해결했습니다 중복되므로 이슈를 닫습니다
