### ISSUE TITLE
보트라이더 관전자 버그

### ISSUE THREAD

**Issue by happy-spark** [IngGameTeam/inggame#178]
보트라이더가 진행중인 상황에서 관전자로 들어가면 다음 사진과 같이 관전자에게도 보트가 생깁니다.

![image](https://user-images.githubusercontent.com/107300540/200512007-3fc7d862-5982-48fd-9766-c0598033ccc3.png)

**Comment by Bruce0203** [comment]
해결했습니다 https://github.com/IngGameTeam/inggame/commit/bd58339a453458e36462a4b713b051cac5a947b2
