### ISSUE TITLE
새 게임

### ISSUE THREAD

**Issue by Monday-blues** [IngGameTeam/inggame#223]
좀 복잡한 게임 구현 가능? 
미니게임속 미니게임 느낌으로 gui내에서 뭐 포커 원카드 체스 이런 보드게임으로 앙서버 돈걸수 있게 그에따라 서버내 재화의 사용처도 늘리고...

**Comment by Bruce0203** [comment]
이거

**Comment by Bruce0203** [comment]
반려하겠습니다
