### ISSUE TITLE
간단한 플러그인 배포(수정)

### ISSUE THREAD

**Issue by andrewwindsor** [IngGameTeam/inggame#63]
/pluginsupload <플러그인네임> 혹은 /plup <플러그인네임> 으로 플러그인을 https://inggameteam.github.io/inggame/ 으로 업로드를 시킵니다. ( 예 : /plup abcd = 플러그인 abcd를 업로드 )

**Comment by Bruce0203** [comment]
개발한 마크 플긴을 마크 명령어로 배포한다는 얘기인데 보통 마크에서 플긴을 개발하지 않고 좋은 IDE 프로그램으로 개발합니다. 
그런데 플러그인을 통해 마크 안에서 제작한 걸 내보내기 기능을 만들고 https://inggameteam.github.io/inggame/ 로 배포하는 아이디어가 좋습니다. 그리고 내보내기 파일이 플러그인 .jar 로 만들어지게 하면 좋을 것 같습니다. 아니면 새로운 온라인 플랫폼을 통해 업로드하고 다운로드해도 좋겠네요.
