### ISSUE TITLE
소스 폴더 구조 변경 요청

### ISSUE THREAD

**Issue by Bruce0203** [IngGameTeam/inggame#66]
**당신의 기능 요청은 문제와 관련이 있습니까? 설명 좀 해 주세요.**
문제가 무엇인지 명확하고 간결한 설명. 
문제가 뭐냐면요, 소스 파일 폴더가 src/main/kotlin 으로 너무 깁니다.

**원하는 솔루션에 대해 설명하십시오.**
발생하려는 작업에 대한 명확하고 간결한 설명.
src 로 줄이고 testSrc 로 분리합시다

**고려했던 대안을 설명하십시오.**
고려했던 대체 솔루션 또는 기능에 대한 명확하고 간결한 설명.

**Comment by Bruce0203** [comment]
네네 좋은 생각입니다

**Comment by entrypointkr** [comment]
src/main/lang 형식을 굳이 바꾼 프로젝트는 한번도 못봤는데 괜찮겠습니까

**Comment by Bruce0203** [comment]
> src/main/lang 형식을 굳이 바꾼 프로젝트는 한번도 못봤는데 괜찮겠습니까

다른 분들이 이해 하겠다고 충분히 봅니다. 하나도 헷갈리지 않게 충분히 가능하다는 눈길로 볼겁니다

**Comment by Bruce0203** [comment]
예쁘게 보이기 위한 건데 그닥 작업의 효율을 높여주지도 않으니 사실 너무 어려워서 포기합니다!
