### ISSUE TITLE
밀치기 막대기 

### ISSUE THREAD

**Issue by qwddlqslek** [IngGameTeam/inggame#83]
**당신의 기능 요청은 문제와 관련이 있습니까? 설명 좀 해 주세요.**
문제가 무엇인지 명확하고 간결한 설명. 

**원하는 솔루션에 대해 설명하십시오.**
발생하려는 작업에 대한 명확하고 간결한 설명.

**고려했던 대안을 설명하십시오.**
고려했던 대체 솔루션 또는 기능에 대한 명확하고 간결한 설명.

**Comment by qwddlqslek** [comment]
밀막 추가 하면 재밌을거 같음 로비에서 포인트 한 3000?

**Comment by Bruce0203** [comment]
완료함
