### ISSUE TITLE
빌드배틀 우승자의 작품을 보여주세요

### ISSUE THREAD

**Issue by Bruce0203** [IngGameTeam/inggame#95]
**당신의 기능 요청은 문제와 관련이 있습니까? 설명 좀 해 주세요.**
문제가 무엇인지 명확하고 간결한 설명. 

**원하는 솔루션에 대해 설명하십시오.**
발생하려는 작업에 대한 명확하고 간결한 설명.

**고려했던 대안을 설명하십시오.**
고려했던 대체 솔루션 또는 기능에 대한 명확하고 간결한 설명.

**Comment by Bruce0203** [comment]
이미 그러하네요

**Comment by yejunho10** [comment]
역대 우승자 말하는듯
